### ISSUE TITLE
Angular events like 'ng-click' etc are not working 

### ISSUE THREAD

**Issue by praveenhumse** [yads/ngTinyScrollbar#13]
I have added 'ngTinyScrollbar' module dependency in my project.
looks like all angular events which were working have stopped working after injection of the module

**Comment by yads** [comment]
Ok, can you post some code that isn't working?

**Comment by praveenhumse** [comment]
<div class="p3rMiddleBodyCommon ovqMainBoxMargin" x-ng-controller="myCtrl1"  scrollbar>
.
.
code goes here
.
.
</div>
It was not working..


When I Added nested div under it. as shown below and removed scroll bar directive from the main div

<div class="p3rMiddleBodyCommon ovqMainBoxMargin" x-ng-controller="myCtrl1"  >
.<div id="ovq" scrollbar>
.
code goes here
.
.
</div>
</div>

 everything started working as usual..

problem is solved but did not understand the difference in behaviour

**Comment by yads** [comment]
I think you forgot to put the markup in your post. Might be useful to others and if there is a bug I could track it down.

**Comment by praveenhumse** [comment]
I have updated the comment.. please check

**Comment by yads** [comment]
That's definitely not expected behaviour. I couldn't see in your markup how you specify the mouse events. FWIW, I haven't experienced this issue in my projects. Is it possible you are using `z-index` in your CSS on some of the elements?
